apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-firstboot
  namespace: {{ .Namespace }}
data:
  galera.cnf: |
    [galera]
    wsrep_on = ON
    wsrep_provider = /usr/lib/galera/libgalera_smm.so
    wsrep_sst_method = mariabackup
    {{ if eq .StepName "firstboot_config" -}}
    wsrep_cluster_address = gcomm://{{ .Name }}-bootstrap-svc,{{ $.Name }}-{{ $.OperatorName }}-0{{ range $i, $v := untilStep 1 (int .Params.NODE_COUNT) 1 }},{{ $.Name }}-{{ $.OperatorName }}-{{ $v }}{{end}}
    {{ else -}}
    wsrep_cluster_address = {{ $.Name }}-galera-0{{ range $i, $v := untilStep 1 (int .Params.NODE_COUNT) 1 }},{{ $.Name }}-galera-{{ $v }}{{end}}
    {{ end -}}
    wsrep_sst_auth = "root:{{ .Params.MYSQL_ROOT_PASSWORD }}"
    binlog_format = ROW
